//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class archiveReports
    {
        public int id { get; set; }
        public int reportsId { get; set; }
    
        public virtual reports reports { get; set; }
    }
}
