//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magnit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PROGADB1Entities : DbContext
    {
        public PROGADB1Entities()
            : base("name=PROGADB1Entities")
        {
        }

        private static PROGADB1Entities _instance;
        public static PROGADB1Entities GetContext()
        {
            if (_instance == null)
                _instance = new PROGADB1Entities();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<archiveReports> archiveReports { get; set; }
        public virtual DbSet<reports> reports { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<userloggs> userloggs { get; set; }
    }
}
