//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace magnit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public string id { get; set; }
        public string title { get; set; }
        public string priceForHour { get; set; }
    }
}
